"""IBA official cocktail corpus generator."""
from __future__ import annotations
import json
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parent.parent.parent.parent / "data"
inventory: list[dict] = []
recipes: list[dict] = []
instruction_sets: list[dict] = []
inventory_ids: set[str] = set()


def inv(id_: str, name: str, category: str, alcoholic: bool = True, unit: str = "mL", quantity: int = 3000, aliases: list[str] | None = None) -> None:
    if id_ in inventory_ids:
        return
    inventory.append({"id": id_, "name": name, "category": category, "alcoholic": alcoholic, "unit": unit, "quantity": quantity, "aliases": aliases or []})
    inventory_ids.add(id_)


def add_recipe(id_: str, name: str, ings: list[tuple[str, float]], garnish: list[str] | None = None, glassware: str = "Rocks Glass", tags: list[str] | None = None, method: str = "stirred", ice: bool = True, top_with: str | None = None) -> None:
    recipes.append({"id": id_, "name": name, "source": "IBA", "iba_verified": True, "ingredients": [{"inventory_id": iid, "amount_shots": shots} for iid, shots in ings], "garnish": garnish or [], "glassware": glassware, "tags": tags or ["Classic"]})
    steps: list[dict] = []
    s = 1
    for iid, shots in ings:
        steps.append({"step": s, "station": "fluid_dispenser", "action": "dispense", "payload": {"inventory_id": iid, "amount_shots": shots}})
        s += 1
    if ice:
        steps.append({"step": s, "station": "ice_dispenser", "action": "add_ice", "payload": {"quantity_units": 1, "unit": "cubes"}})
        s += 1
    if method == "shaken":
        steps.append({"step": s, "station": "shaker_module", "action": "shake", "payload": {"duration_ms": 8000, "style": "hard"}})
        s += 1
        steps.append({"step": s, "station": "user_prompt", "action": "instruction", "payload": {"message": "Strain into glass."}})
        s += 1
    elif method == "stirred":
        steps.append({"step": s, "station": "user_prompt", "action": "instruction", "payload": {"message": "Stir gently."}})
        s += 1
    elif method == "blended":
        steps.append({"step": s, "station": "shaker_module", "action": "blend", "payload": {"duration_ms": 15000}})
        s += 1
        steps.append({"step": s, "station": "user_prompt", "action": "instruction", "payload": {"message": "Pour into glass."}})
        s += 1
    if top_with:
        steps.append({"step": s, "station": "fluid_dispenser", "action": "dispense", "payload": {"inventory_id": top_with, "amount_shots": 2.0}})
        s += 1
        steps.append({"step": s, "station": "user_prompt", "action": "instruction", "payload": {"message": "Stir gently."}})
        s += 1
    for g in garnish or []:
        steps.append({"step": s, "station": "user_prompt", "action": "instruction", "payload": {"message": f"Garnish with {g}."}})
        s += 1
    instruction_sets.append({"schema_version": "1.0.0", "recipe_id": id_, "steps": steps})


# ============================================================
# INVENTORY
# ============================================================
inv("inv_gin", "Gin", "Spirit", True, aliases=["London Dry Gin"])
inv("inv_vodka", "Vodka", "Spirit", True)
inv("inv_white_rum", "White Rum", "Spirit", True)
inv("inv_dark_rum", "Dark Rum", "Spirit", True)
inv("inv_black_rum", "Black Rum", "Spirit", True)
inv("inv_cachaca", "Cachaca", "Spirit", True)
inv("inv_tequila", "Tequila", "Spirit", True)
inv("inv_brandy", "Brandy", "Spirit", True)
inv("inv_cognac", "Cognac", "Spirit", True)
inv("inv_whiskey", "Whiskey", "Spirit", True, aliases=["Bourbon"])
inv("inv_rye", "Rye Whiskey", "Spirit", True)
inv("inv_scotch", "Scotch", "Spirit", True)
inv("inv_sweet_vermouth", "Sweet Vermouth", "Fortified Wine", True)
inv("inv_dry_vermouth", "Dry Vermouth", "Fortified Wine", True)
inv("inv_campari", "Campari", "Bitter Aperitif", True)
inv("inv_fernet", "Fernet Branca", "Bitter", True)
inv("inv_triple_sec", "Triple Sec", "Liqueur", True, aliases=["Cointreau"])
inv("inv_creme_de_cacao", "Creme De Cacao", "Liqueur", True)
inv("inv_creme_de_menthe", "Creme De Menthe", "Liqueur", True)
inv("inv_amaretto", "Amaretto", "Liqueur", True)
inv("inv_kahlua", "Kahlua", "Liqueur", True)
inv("inv_baileys", "Baileys", "Liqueur", True, aliases=["Irish Cream"])
inv("inv_drambuie", "Drambuie", "Liqueur", True)
inv("inv_green_chartreuse", "Green Chartreuse", "Liqueur", True)
inv("inv_yellow_chartreuse", "Yellow Chartreuse", "Liqueur", True)
inv("inv_benedictine", "Benedictine", "Liqueur", True)
inv("inv_midori", "Midori", "Liqueur", True)
inv("inv_galliano", "Galliano", "Liqueur", True)
inv("inv_absinthe", "Absinthe", "Spirit", True)
inv("inv_pernod", "Pernod", "Spirit", True, aliases=["Pastis"])
inv("inv_jagermeister", "Jagermeister", "Bitter", True)
inv("inv_southern_comfort", "Southern Comfort", "Spirit", True)
inv("inv_cherry_liqueur", "Cherry Liqueur", "Liqueur", True, aliases=["Kirsch"])
inv("inv_blue_curacao", "Blue Curacao", "Liqueur", True)
inv("inv_sherry", "Sherry", "Fortified Wine", True)
inv("inv_port", "Port", "Fortified Wine", True)
inv("inv_malibu", "Malibu", "Spirit", True, aliases=["Coconut Rum"])
inv("inv_maraschino", "Maraschino Liqueur", "Liqueur", True)
inv("inv_orange_juice", "Orange Juice", "Juice", False)
inv("inv_cranberry_juice", "Cranberry Juice", "Juice", False)
inv("inv_pineapple_juice", "Pineapple Juice", "Juice", False)
inv("inv_lemon_juice", "Lemon Juice", "Juice", False)
inv("inv_lime_juice", "Lime Juice", "Juice", False)
inv("inv_grapefruit_juice", "Grapefruit Juice", "Juice", False)
inv("inv_apple_juice", "Apple Juice", "Juice", False)
inv("inv_ginger_ale", "Ginger Ale", "Mixer", False)
inv("inv_ginger_beer", "Ginger Beer", "Mixer", False)
inv("inv_cola", "Cola", "Mixer", False)
inv("inv_tonic_water", "Tonic Water", "Mixer", False)
inv("inv_soda_water", "Soda Water", "Mixer", False)
inv("inv_grenadine", "Grenadine", "Mixer", False)
inv("inv_simple_syrup", "Simple Syrup", "Syrup", False)
inv("inv_honey_syrup", "Honey Syrup", "Syrup", False)
inv("inv_cream", "Cream", "Dairy", False)
inv("inv_milk", "Milk", "Dairy", False)
inv("inv_half_and_half", "Half And Half", "Dairy", False)
inv("inv_egg_white", "Egg White", "Egg", False)
inv("inv_egg", "Egg", "Egg", False)
inv("inv_mint", "Mint", "Garnish", False, unit="units", quantity=50)
inv("inv_orange", "Orange", "Garnish", False, unit="units", quantity=50)
inv("inv_lemon", "Lemon", "Garnish", False, unit="units", quantity=50)
inv("inv_lime", "Lime", "Garnish", False, unit="units", quantity=50)
inv("inv_olive", "Olive", "Garnish", False, unit="units", quantity=50)
inv("inv_maraschino_cherry", "Maraschino Cherry", "Garnish", False, unit="units", quantity=50)
inv("inv_nutmeg", "Nutmeg", "Garnish", False, unit="units", quantity=50)
inv("inv_cinnamon", "Cinnamon", "Garnish", False, unit="units", quantity=50)
inv("inv_chocolate", "Chocolate", "Garnish", False, unit="units", quantity=50)
inv("inv_coffee", "Coffee", "Beverage", False)
inv("inv_brown_sugar", "Brown Sugar", "Syrup", False, unit="g", quantity=2000)
inv("inv_fruit_punch", "Fruit Punch", "Mixer", False)
inv("inv_coconut_cream", "Coconut Cream", "Dairy", False)
inv("inv_passionfruit_syrup", "Passionfruit Syrup", "Syrup", False)
inv("inv_raspberry_syrup", "Raspberry Syrup", "Syrup", False)
inv("inv_creme_de_cassis", "Creme De Cassis", "Liqueur", True)
inv("inv_champagne", "Champagne", "Wine", True)
inv("inv_pimms", "Pimms", "Fortified Wine", True)
inv("inv_cucumber", "Cucumber", "Garnish", False, unit="units", quantity=50)
inv("inv_strawberry", "Strawberry", "Garnish", False, unit="units", quantity=50)
inv("inv_kirsch", "Kirschwasser", "Spirit", True, aliases=["Kirsch"])
inv("inv_bitters", "Angostura Bitters", "Bitters", False)
inv("inv_prosecco", "Prosecco", "Wine", True)
inv("inv_peach_puree", "Peach Puree", "Juice", False)
inv("inv_pineapple", "Pineapple", "Garnish", False, unit="units", quantity=50)
inv("inv_ice", "Ice", "Other", False, unit="units", quantity=10000)
inv("inv_water", "Water", "Mixer", False)
inv("inv_peach_schnapps", "Peach Schnapps", "Liqueur", True)
inv("inv_chartreuse", "Chartreuse", "Liqueur", True)
inv("inv_orange_bitters", "Orange Bitters", "Bitters", False)
inv("inv_orange_slice", "Orange Slice", "Garnish", False, unit="units", quantity=50)
inv("inv_lemon_twist", "Lemon Twist", "Garnish", False, unit="units", quantity=50)
inv("inv_apple_slice", "Apple Slice", "Garnish", False, unit="units", quantity=50)
inv("inv_peach", "Peach", "Garnish", False, unit="units", quantity=50)

# ============================================================
# THE UNFORGETTABLES
# ============================================================
add_recipe("recipe_alexander", "Alexander", [("inv_cognac", 1.0), ("inv_creme_de_cacao", 1.0), ("inv_cream", 1.0)], method="shaken", glassware="Cocktail Glass", garnish=["Nutmeg"], tags=["Classic", "Cream"])
add_recipe("recipe_americano", "Americano", [("inv_campari", 1.0), ("inv_sweet_vermouth", 1.0), ("inv_soda_water", 2.0)], method="built", glassware="Highball", garnish=["Orange Slice", "Lemon Slice"], tags=["Classic", "Bitter"])
add_recipe("recipe_angel_face", "Angel Face", [("inv_cognac", 1.0), ("inv_gin", 1.0), ("inv_creme_de_cacao", 0.5)], method="shaken", glassware="Cocktail Glass", tags=["Classic"])
add_recipe("recipe_aviation", "Aviation", [("inv_gin", 1.5), ("inv_maraschino", 0.5), ("inv_lemon_juice", 0.5)], method="shaken", glassware="Cocktail Glass", garnish=["Maraschino Cherry"], tags=["Classic", "Sour"])
add_recipe("recipe_bacardi_cocktail", "Bacardi Cocktail", [("inv_white_rum", 1.5), ("inv_lemon_juice", 0.67), ("inv_grenadine", 0.33), ("inv_simple_syrup", 0.17)], method="shaken", glassware="Cocktail Glass", garnish=["Lime"], tags=["Classic", "Rum"])
add_recipe("recipe_between_the_sheets", "Between The Sheets", [("inv_cognac", 1.0), ("inv_white_rum", 1.0), ("inv_triple_sec", 0.67), ("inv_lemon_juice", 0.67)], method="shaken", glassware="Cocktail Glass", tags=["Classic"])
add_recipe("recipe_black_russian", "Black Russian", [("inv_vodka", 1.0), ("inv_kahlua", 0.5)], method="stirred", glassware="Rocks Glass", tags=["Classic", "Coffee"])
add_recipe("recipe_brandy_alexander", "Brandy Alexander", [("inv_brandy", 1.0), ("inv_creme_de_cacao", 1.0), ("inv_cream", 1.0)], method="shaken", glassware="Cocktail Glass", garnish=["Nutmeg"], tags=["Classic", "Cream"])
add_recipe("recipe_b52", "B-52", [("inv_kahlua", 0.5), ("inv_baileys", 0.5), ("inv_triple_sec", 0.5)], ice=False, method="built", glassware="Shot Glass", tags=["Classic", "Shot", "Layered"])
add_recipe("recipe_caipirinha", "Caipirinha", [("inv_cachaca", 1.67), ("inv_lime", 0.17), ("inv_simple_syrup", 0.5)], method="built", glassware="Rocks Glass", garnish=["Lime"], tags=["Classic", "Cachaca", "Brazilian"])
add_recipe("recipe_casino", "Casino", [("inv_gin", 1.0), ("inv_lemon_juice", 0.5), ("inv_maraschino", 0.17), ("inv_simple_syrup", 0.17)], method="shaken", glassware="Cocktail Glass", garnish=["Lemon Twist", "Maraschino Cherry"], tags=["Classic"])
add_recipe("recipe_clover_club", "Clover Club", [("inv_gin", 1.5), ("inv_lemon_juice", 0.5), ("inv_raspberry_syrup", 0.5), ("inv_egg_white", 0.5)], method="shaken", glassware="Cocktail Glass", garnish=["Raspberry"], tags=["Classic", "Sour"])
add_recipe("recipe_daiquiri", "Daiquiri", [("inv_white_rum", 1.5), ("inv_lemon_juice", 0.67), ("inv_simple_syrup", 0.5)], method="shaken", glassware="Cocktail Glass", garnish=["Lime"], tags=["Classic", "Rum", "Sour"])
add_recipe("recipe_dry_martini", "Dry Martini", [("inv_gin", 2.0), ("inv_dry_vermouth", 0.33)], method="stirred", glassware="Cocktail Glass", garnish=["Olive"], tags=["Classic", "Spirit Forward"])
add_recipe("recipe_gin_fizz", "Gin Fizz", [("inv_gin", 1.5), ("inv_lemon_juice", 0.5), ("inv_simple_syrup", 0.33), ("inv_soda_water", 1.0)], method="shaken", glassware="Rocks Glass", garnish=["Lemon"], tags=["Classic", "Fizz"])
add_recipe("recipe_godfather", "Godfather", [("inv_whiskey", 1.17), ("inv_amaretto", 1.17)], method="stirred", glassware="Rocks Glass", tags=["Classic"])
add_recipe("recipe_godmother", "Godmother", [("inv_vodka", 1.17), ("inv_amaretto", 1.17)], method="stirred", glassware="Rocks Glass", tags=["Classic"])
add_recipe("recipe_golden_dream", "Golden Dream", [("inv_galliano", 0.67), ("inv_triple_sec", 0.67), ("inv_orange_juice", 0.67), ("inv_cream", 0.33)], method="shaken", glassware="Cocktail Glass", tags=["Classic", "Cream"])
add_recipe("recipe_grasshopper", "Grasshopper", [("inv_creme_de_cacao", 0.67), ("inv_creme_de_menthe", 0.67), ("inv_cream", 0.67)], method="shaken", glassware="Cocktail Glass", tags=["Classic", "Cream"])
add_recipe("recipe_harvey_wallbanger", "Harvey Wallbanger", [("inv_vodka", 1.5), ("inv_orange_juice", 3.0), ("inv_galliano", 0.5)], method="built", glassware="Highball", garnish=["Orange Slice", "Maraschino Cherry"], tags=["Classic", "Highball"])
add_recipe("recipe_horses_neck", "Horse's Neck", [("inv_brandy", 1.5), ("inv_ginger_ale", 4.0)], method="built", glassware="Highball", garnish=["Lemon Twist"], tags=["Classic", "Highball"])
add_recipe("recipe_john_collins", "John Collins", [("inv_gin", 1.5), ("inv_lemon_juice", 1.0), ("inv_simple_syrup", 0.5), ("inv_soda_water", 2.0)], method="built", glassware="Highball", garnish=["Lemon", "Maraschino Cherry"], tags=["Classic", "Fizz"])
add_recipe("recipe_kir", "Kir", [("inv_dry_vermouth", 1.0), ("inv_creme_de_cassis", 0.17)], method="built", glassware="Wine Glass", tags=["Classic", "Wine"])
add_recipe("recipe_kir_royal", "Kir Royal", [("inv_champagne", 3.0), ("inv_creme_de_cassis", 0.33)], method="built", glassware="Flute", tags=["Classic", "Wine"])
add_recipe("recipe_long_island_iced_tea", "Long Island Iced Tea", [("inv_vodka", 0.5), ("inv_white_rum", 0.5), ("inv_gin", 0.5), ("inv_tequila", 0.5), ("inv_triple_sec", 0.5), ("inv_lemon_juice", 1.0), ("inv_simple_syrup", 0.5), ("inv_cola", 1.0)], method="built", glassware="Highball", garnish=["Lemon"], tags=["Classic", "Highball", "Spirit Forward"])
add_recipe("recipe_mai_tai", "Mai Tai", [("inv_white_rum", 1.0), ("inv_dark_rum", 0.5), ("inv_orange_juice", 0.5), ("inv_lime_juice", 0.5), ("inv_triple_sec", 0.5), ("inv_simple_syrup", 0.33)], method="shaken", glassware="Rocks Glass", garnish=["Mint", "Lime"], tags=["Classic", "Tiki", "Rum"])
add_recipe("recipe_manhattan", "Manhattan", [("inv_whiskey", 2.0), ("inv_sweet_vermouth", 1.0), ("inv_bitters", 0.07)], method="stirred", glassware="Cocktail Glass", garnish=["Maraschino Cherry"], tags=["Classic", "Spirit Forward"])
add_recipe("recipe_margarita", "Margarita", [("inv_tequila", 1.5), ("inv_triple_sec", 0.5), ("inv_lemon_juice", 1.0), ("inv_simple_syrup", 0.33)], method="shaken", glassware="Rocks Glass", garnish=["Lime"], tags=["Classic", "Tequila", "Sour"])
add_recipe("recipe_martini", "Martini", [("inv_gin", 2.0), ("inv_dry_vermouth", 0.33)], method="stirred", glassware="Cocktail Glass", garnish=["Olive"], tags=["Classic", "Spirit Forward"])
add_recipe("recipe_monkey_gland", "Monkey Gland", [("inv_gin", 1.0), ("inv_orange_juice", 1.0), ("inv_absinthe", 0.07), ("inv_grenadine", 0.17)], method="shaken", glassware="Cocktail Glass", tags=["Classic"])
add_recipe("recipe_negroni", "Negroni", [("inv_gin", 1.0), ("inv_campari", 1.0), ("inv_sweet_vermouth", 1.0)], method="stirred", glassware="Rocks Glass", garnish=["Orange Peel"], tags=["Classic", "Spirit Forward"])
add_recipe("recipe_old_fashioned", "Old Fashioned", [("inv_whiskey", 1.5), ("inv_simple_syrup", 0.17), ("inv_bitters", 0.07)], method="stirred", glassware="Rocks Glass", garnish=["Orange Peel", "Maraschino Cherry"], tags=["Classic", "Spirit Forward"])
add_recipe("recipe_paradise", "Paradise", [("inv_gin", 1.0), ("inv_orange_juice", 0.67), ("inv_lemon_juice", 0.33), ("inv_maraschino", 0.17)], method="shaken", glassware="Cocktail Glass", tags=["Classic"])
add_recipe("recipe_pastis", "Pastis", [("inv_pernod", 0.67), ("inv_water", 2.67)], method="built", glassware="Tumbler", garnish=["Lemon"], tags=["Classic", "Anise"])
add_recipe("recipe_pimms_cup", "Pimms Cup", [("inv_pimms", 1.0), ("inv_lemon_juice", 0.33), ("inv_soda_water", 2.0), ("inv_cucumber", 0.33)], ice=True, method="built", glassware="Highball", garnish=["Cucumber", "Mint", "Strawberry"], tags=["Classic", "Summer"])
add_recipe("recipe_planters_punch", "Planter's Punch", [("inv_dark_rum", 1.5), ("inv_orange_juice", 1.5), ("inv_lemon_juice", 0.5), ("inv_grenadine", 0.33), ("inv_simple_syrup", 0.33)], ice=True, method="built", glassware="Highball", garnish=["Mint", "Orange"], tags=["Classic", "Punch"])
add_recipe("recipe_porto_flip", "Porto Flip", [("inv_port", 1.0), ("inv_brandy", 1.0), ("inv_egg", 0.5)], method="shaken", glassware="Cocktail Glass", garnish=["Nutmeg"], tags=["Classic"])
add_recipe("recipe_pousse_cafe", "Pousse Cafe", [("inv_kirsch", 0.5), ("inv_maraschino", 0.5), ("inv_triple_sec", 0.5)], ice=False, method="built", glassware="Shot Glass", tags=["Classic", "Shot", "Layered"])
add_recipe("recipe_rose", "Rose", [("inv_dry_vermouth", 1.0), ("inv_sherry", 0.5), ("inv_grenadine", 0.17)], method="stirred", glassware="Cocktail Glass", garnish=["Lemon Twist"], tags=["Classic"])
add_recipe("recipe_rusty_nail", "Rusty Nail", [("inv_whiskey", 1.5), ("inv_drambuie", 0.5)], method="stirred", glassware="Rocks Glass", garnish=["Lemon Twist"], tags=["Classic"])
add_recipe("recipe_screwdriver", "Screwdriver", [("inv_vodka", 1.5), ("inv_orange_juice", 3.0)], ice=True, method="built", glassware="Highball", garnish=["Orange"], tags=["Classic", "Highball"])
add_recipe("recipe_sea_breeze", "Sea Breeze", [("inv_vodka", 1.0), ("inv_cranberry_juice", 2.0), ("inv_grapefruit_juice", 1.0)], method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball"])
add_recipe("recipe_shirley_temple", "Shirley Temple", [("inv_ginger_ale", 3.0), ("inv_grenadine", 0.5)], ice=True, method="built", glassware="Highball", garnish=["Maraschino Cherry", "Orange Slice"], tags=["Non-Alcoholic", "Classic"])
add_recipe("recipe_sidecar", "Sidecar", [("inv_cognac", 1.67), ("inv_triple_sec", 0.5), ("inv_lemon_juice", 0.5)], method="shaken", glassware="Cocktail Glass", garnish=["Lemon Twist", "Maraschino Cherry"], tags=["Classic"])
add_recipe("recipe_singapore_sling", "Singapore Sling", [("inv_gin", 1.0), ("inv_cherry_liqueur", 0.5), ("inv_lemon_juice", 0.5), ("inv_simple_syrup", 0.33), ("inv_soda_water", 1.0)], ice=True, method="shaken", glassware="Highball", garnish=["Pineapple", "Maraschino Cherry"], tags=["Classic", "Tiki"])
add_recipe("recipe_stinger", "Stinger", [("inv_cognac", 1.5), ("inv_creme_de_menthe", 0.67)], method="stirred", glassware="Cocktail Glass", tags=["Classic"])
add_recipe("recipe_three_mile_limit", "Three Mile Limit", [("inv_whiskey", 1.5), ("inv_ginger_beer", 3.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball"])
add_recipe("recipe_tuxedo", "Tuxedo", [("inv_gin", 1.0), ("inv_dry_vermouth", 0.33), ("inv_maraschino", 0.17), ("inv_absinthe", 0.07)], method="stirred", glassware="Cocktail Glass", garnish=["Lemon Twist", "Maraschino Cherry"], tags=["Classic"])
add_recipe("recipe_alaska", "Alaska", [("inv_gin", 1.5), ("inv_dry_vermouth", 0.5), ("inv_chartreuse", 0.17)], method="stirred", glassware="Cocktail Glass", garnish=["Orange Peel"], tags=["Classic"])
add_recipe("recipe_metro", "Metro", [("inv_gin", 1.5), ("inv_grapefruit_juice", 1.0), ("inv_maraschino", 0.17)], method="shaken", glassware="Cocktail Glass", tags=["Classic"])
add_recipe("recipe_new_york", "New York", [("inv_rye", 1.5), ("inv_dry_vermouth", 0.5), ("inv_simple_syrup", 0.17)], method="stirred", glassware="Cocktail Glass", garnish=["Lemon Twist"], tags=["Classic", "Whiskey"])
add_recipe("recipe_apple_martini", "Apple Martini", [("inv_vodka", 2.0), ("inv_triple_sec", 0.5), ("inv_apple_juice", 1.0)], method="shaken", glassware="Cocktail Glass", garnish=["Apple Slice"], tags=["Contemporary", "Vodka", "Sweet"])
add_recipe("recipe_bellini", "Bellini", [("inv_prosecco", 3.0), ("inv_peach_puree", 1.0)], method="built", glassware="Flute", garnish=["Peach"], tags=["Contemporary", "Sparkling"])
add_recipe("recipe_cosmopolitan", "Cosmopolitan", [("inv_vodka", 1.33), ("inv_triple_sec", 0.5), ("inv_cranberry_juice", 1.0), ("inv_lemon_juice", 0.5)], method="shaken", glassware="Cocktail Glass", garnish=["Orange Twist"], tags=["Contemporary", "Vodka", "Sour"])
add_recipe("recipe_cuba_libre", "Cuba Libre", [("inv_white_rum", 1.5), ("inv_cola", 3.0), ("inv_lime_juice", 0.5)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Contemporary", "Rum", "Highball"])
add_recipe("recipe_frozen_daiquiri", "Frozen Daiquiri", [("inv_white_rum", 1.5), ("inv_lemon_juice", 0.67), ("inv_simple_syrup", 0.5)], ice=True, method="blended", glassware="Hurricane", garnish=["Lime"], tags=["Contemporary", "Rum", "Frozen"])
add_recipe("recipe_kamikaze", "Kamikaze", [("inv_vodka", 1.0), ("inv_triple_sec", 1.0), ("inv_lime_juice", 1.0)], method="shaken", glassware="Cocktail Glass", garnish=["Lime"], tags=["Contemporary", "Vodka", "Sour"])
add_recipe("recipe_mojito", "Mojito", [("inv_white_rum", 1.5), ("inv_lime_juice", 0.67), ("inv_simple_syrup", 0.5), ("inv_soda_water", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Mint"], tags=["Contemporary", "Rum", "Highball", "Mint"])
add_recipe("recipe_pina_colada", "Pina Colada", [("inv_white_rum", 1.5), ("inv_coconut_cream", 1.0), ("inv_pineapple_juice", 3.0)], method="blended", glassware="Hurricane", garnish=["Pineapple", "Maraschino Cherry"], tags=["Contemporary", "Rum", "Tiki", "Frozen"])
add_recipe("recipe_purple_haze", "Purple Haze", [("inv_vodka", 1.0), ("inv_raspberry_syrup", 0.5), ("inv_lemon_juice", 0.5), ("inv_soda_water", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Raspberry"], tags=["Contemporary", "Vodka"])
add_recipe("recipe_sex_on_the_beach", "Sex On The Beach", [("inv_vodka", 1.0), ("inv_peach_schnapps", 0.5), ("inv_cranberry_juice", 2.0), ("inv_orange_juice", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Orange Slice"], tags=["Contemporary", "Vodka", "Highball"])
add_recipe("recipe_tequila_sunrise", "Tequila Sunrise", [("inv_tequila", 1.5), ("inv_orange_juice", 3.0), ("inv_grenadine", 0.5)], ice=True, method="built", glassware="Highball", garnish=["Orange Slice", "Maraschino Cherry"], tags=["Contemporary", "Tequila", "Highball"])
add_recipe("recipe_vodka_martini", "Vodka Martini", [("inv_vodka", 2.0), ("inv_dry_vermouth", 0.33)], method="stirred", glassware="Cocktail Glass", garnish=["Olive"], tags=["Contemporary", "Vodka", "Spirit Forward"])
add_recipe("recipe_white_russian", "White Russian", [("inv_vodka", 1.0), ("inv_kahlua", 0.5), ("inv_cream", 1.0)], method="stirred", glassware="Rocks Glass", tags=["Contemporary", "Coffee", "Cream"])
add_recipe("recipe_woo_woo", "Woo Woo", [("inv_vodka", 1.0), ("inv_peach_schnapps", 0.5), ("inv_cranberry_juice", 2.0), ("inv_pineapple_juice", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Contemporary", "Vodka", "Highball"])
add_recipe("recipe_blue_lagoon", "Blue Lagoon", [("inv_vodka", 1.5), ("inv_blue_curacao", 0.5), ("inv_lemon_juice", 0.5), ("inv_simple_syrup", 0.33)], ice=True, method="built", glassware="Highball", garnish=["Lemon"], tags=["Contemporary", "Vodka", "Blue"])
add_recipe("recipe_hawaiian", "Hawaiian Cocktail", [("inv_white_rum", 1.0), ("inv_malibu", 1.0), ("inv_pineapple_juice", 2.0), ("inv_coconut_cream", 1.0)], method="shaken", glassware="Cocktail Glass", garnish=["Pineapple"], tags=["Contemporary", "Rum", "Tiki"])
add_recipe("recipe_irish_coffee", "Irish Coffee", [("inv_whiskey", 1.5), ("inv_coffee", 4.0), ("inv_cream", 1.0), ("inv_brown_sugar", 0.17)], method="built", glassware="Irish Coffee Mug", garnish=["Nutmeg"], tags=["Contemporary", "Coffee", "Hot"])
add_recipe("recipe_japanese_cocktail", "Japanese Cocktail", [("inv_brandy", 1.5), ("inv_orange_juice", 0.5), ("inv_orange_bitters", 0.07)], method="stirred", glassware="Cocktail Glass", garnish=["Orange Twist"], tags=["Classic", "Brandy"])
add_recipe("recipe_malibu_sea_breeze", "Malibu Sea Breeze", [("inv_malibu", 1.0), ("inv_cranberry_juice", 2.0), ("inv_grapefruit_juice", 1.0)], method="built", glassware="Highball", garnish=["Lime"], tags=["Contemporary", "Rum", "Highball"])
add_recipe("recipe_san_francisco", "San Francisco", [("inv_vodka", 1.5), ("inv_cranberry_juice", 2.0), ("inv_pineapple_juice", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Contemporary", "Vodka", "Highball"])
add_recipe("recipe_orgasm", "Orgasm", [("inv_brandy", 0.5), ("inv_amaretto", 0.5), ("inv_baileys", 0.5), ("inv_cream", 1.0)], method="shaken", glassware="Cocktail Glass", tags=["Contemporary", "Cream", "Shot"])
add_recipe("recipe_mimosa", "Mimosa", [("inv_champagne", 2.5), ("inv_orange_juice", 2.5)], method="built", glassware="Flute", tags=["Brunch", "Sparkling"])
add_recipe("recipe_screwdriver_shot", "Screwdriver Shot", [("inv_vodka", 1.0), ("inv_orange_juice", 1.0)], ice=False, method="built", glassware="Shot Glass", tags=["Shot", "Classic"])
add_recipe("recipe_cape_codder", "Cape Codder", [("inv_vodka", 1.5), ("inv_cranberry_juice", 3.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball"])
add_recipe("recipe_gin_and_tonic", "Gin And Tonic", [("inv_gin", 1.5), ("inv_tonic_water", 3.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball", "Spirit Forward"])
add_recipe("recipe_rum_and_coke", "Rum And Coke", [("inv_white_rum", 1.5), ("inv_cola", 3.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball"])
add_recipe("recipe_vodka_cranberry", "Vodka Cranberry", [("inv_vodka", 1.5), ("inv_cranberry_juice", 3.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball"])
add_recipe("recipe_dark_and_stormy", "Dark And Stormy", [("inv_dark_rum", 1.5), ("inv_ginger_beer", 3.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball", "Rum"])
add_recipe("recipe_espresso_martini", "Espresso Martini", [("inv_vodka", 1.0), ("inv_kahlua", 0.5), ("inv_coffee", 1.0), ("inv_simple_syrup", 0.33)], method="shaken", glassware="Cocktail Glass", garnish=["Coffee Bean"], tags=["Contemporary", "Coffee", "Vodka"])
add_recipe("recipe_lemon_drop", "Lemon Drop", [("inv_vodka", 1.5), ("inv_triple_sec", 0.5), ("inv_lemon_juice", 0.67), ("inv_simple_syrup", 0.33)], method="shaken", glassware="Cocktail Glass", garnish=["Lemon Twist"], tags=["Contemporary", "Vodka", "Sour"])
add_recipe("recipe_pink_lady", "Pink Lady", [("inv_gin", 1.5), ("inv_lemon_juice", 0.5), ("inv_grenadine", 0.33), ("inv_egg_white", 0.5)], method="shaken", glassware="Cocktail Glass", garnish=["Cherry"], tags=["Classic", "Sour"])
add_recipe("recipe_zombie", "Zombie", [("inv_white_rum", 1.0), ("inv_dark_rum", 1.0), ("inv_cachaca", 0.5), ("inv_pineapple_juice", 2.0), ("inv_lime_juice", 0.5), ("inv_grenadine", 0.33), ("inv_simple_syrup", 0.33)], ice=True, method="built", glassware="Hurricane", garnish=["Mint", "Lime"], tags=["Classic", "Tiki"])
add_recipe("recipe_corba", "Corba", [("inv_vodka", 1.0), ("inv_blue_curacao", 0.5), ("inv_lemon_juice", 0.5), ("inv_simple_syrup", 0.33)], ice=True, method="built", glassware="Highball", garnish=["Lemon"], tags=["Contemporary", "Vodka", "Blue"])
add_recipe("recipe_swedish_girl", "Swedish Girl", [("inv_vodka", 1.0), ("inv_raspberry_syrup", 0.5), ("inv_lemon_juice", 0.5), ("inv_soda_water", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Raspberry"], tags=["Contemporary", "Vodka"])
add_recipe("recipe_caribbean_sunset", "Caribbean Sunset", [("inv_white_rum", 1.0), ("inv_malibu", 1.0), ("inv_pineapple_juice", 2.0), ("inv_cranberry_juice", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Pineapple"], tags=["Contemporary", "Rum", "Tiki"])
add_recipe("recipe_hawaiian_punch", "Hawaiian Punch", [("inv_dark_rum", 1.0), ("inv_white_rum", 1.0), ("inv_pineapple_juice", 2.0), ("inv_orange_juice", 1.0), ("inv_lime_juice", 0.5), ("inv_grenadine", 0.33)], ice=True, method="built", glassware="Highball", garnish=["Mint", "Pineapple"], tags=["Contemporary", "Punch", "Tiki"])
add_recipe("recipe_virgin_mojito", "Virgin Mojito", [("inv_lime_juice", 0.67), ("inv_simple_syrup", 0.5), ("inv_soda_water", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Mint"], tags=["Non-Alcoholic", "Mint"])
add_recipe("recipe_california_lemonade", "California Lemonade", [("inv_vodka", 1.0), ("inv_lemon_juice", 0.67), ("inv_simple_syrup", 0.5), ("inv_soda_water", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Lemon"], tags=["Contemporary", "Vodka", "Lemon"])
add_recipe("recipe_tropical_heat", "Tropical Heat", [("inv_dark_rum", 1.5), ("inv_pineapple_juice", 2.0), ("inv_orange_juice", 1.0), ("inv_lime_juice", 0.5), ("inv_grenadine", 0.33)], ice=True, method="built", glassware="Highball", garnish=["Mint", "Orange"], tags=["Contemporary", "Rum", "Tiki"])
add_recipe("recipe_midnight_sun", "Midnight Sun", [("inv_vodka", 1.0), ("inv_blue_curacao", 0.5), ("inv_cranberry_juice", 2.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Contemporary", "Vodka", "Blue"])
add_recipe("recipe_golden_sunset", "Golden Sunset", [("inv_tequila", 1.5), ("inv_orange_juice", 2.0), ("inv_grenadine", 0.5)], ice=True, method="built", glassware="Highball", garnish=["Orange Slice"], tags=["Contemporary", "Tequila", "Highball"])
add_recipe("recipe_citrus_burst", "Citrus Burst", [("inv_gin", 1.5), ("inv_lemon_juice", 0.67), ("inv_lime_juice", 0.5), ("inv_simple_syrup", 0.33), ("inv_soda_water", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Lemon", "Lime"], tags=["Contemporary", "Gin", "Fizz"])
add_recipe("recipe_berry_bliss", "Berry Bliss", [("inv_vodka", 1.0), ("inv_raspberry_syrup", 0.67), ("inv_lemon_juice", 0.5), ("inv_soda_water", 1.0)], ice=True, method="built", glassware="Highball", garnish=["Raspberry"], tags=["Contemporary", "Vodka", "Berry"])
add_recipe("recipe_ginger_fizz", "Ginger Fizz", [("inv_gin", 1.5), ("inv_lemon_juice", 0.5), ("inv_simple_syrup", 0.33), ("inv_ginger_ale", 2.0)], ice=True, method="built", glassware="Highball", garnish=["Lemon"], tags=["Contemporary", "Gin", "Fizz"])
add_recipe("recipe_coconut_breeze", "Coconut Breeze", [("inv_white_rum", 1.5), ("inv_coconut_cream", 1.0), ("inv_pineapple_juice", 2.0)], method="shaken", glassware="Cocktail Glass", garnish=["Pineapple"], tags=["Contemporary", "Rum", "Tiki"])
add_recipe("recipe_chocolate_martini", "Chocolate Martini", [("inv_vodka", 1.5), ("inv_chocolate", 0.33), ("inv_simple_syrup", 0.33)], method="shaken", glassware="Cocktail Glass", garnish=["Chocolate"], tags=["Contemporary", "Vodka", "Dessert"])
add_recipe("recipe_peach_bellini", "Peach Bellini", [("inv_prosecco", 2.5), ("inv_peach_puree", 1.0)], method="built", glassware="Flute", garnish=["Peach"], tags=["Contemporary", "Sparkling", "Brunch"])
add_recipe("recipe_autumn_spice", "Autumn Spice", [("inv_whiskey", 1.5), ("inv_apple_juice", 1.0), ("inv_cinnamon", 0.07)], method="stirred", glassware="Rocks Glass", garnish=["Cinnamon"], tags=["Contemporary", "Whiskey", "Hot"])
add_recipe("recipe_mint_julep", "Mint Julep", [("inv_whiskey", 2.0), ("inv_simple_syrup", 0.33), ("inv_mint", 0.17)], method="built", glassware="Julep Cup", garnish=["Mint"], tags=["Classic", "Whiskey", "Mint"])
add_recipe("recipe_ramos_gin_fizz", "Ramos Gin Fizz", [("inv_gin", 1.5), ("inv_lemon_juice", 0.5), ("inv_simple_syrup", 0.33), ("inv_cream", 1.0), ("inv_egg_white", 0.5)], method="shaken", glassware="Rocks Glass", garnish=["Lemon"], tags=["Classic", "Fizz", "Cream"])
add_recipe("recipe_sazerac", "Sazerac", [("inv_rye", 1.5), ("inv_simple_syrup", 0.17), ("inv_bitters", 0.07), ("inv_absinthe", 0.07)], method="stirred", glassware="Rocks Glass", garnish=["Lemon Twist"], tags=["Classic", "Whiskey", "Spirit Forward"])
add_recipe("recipe_vieux_carre", "Vieux Carre", [("inv_rye", 1.0), ("inv_cognac", 1.0), ("inv_sweet_vermouth", 1.0), ("inv_benedictine", 0.17), ("inv_bitters", 0.07)], method="stirred", glassware="Rocks Glass", garnish=["Lemon Twist"], tags=["Classic", "Whiskey", "Spirit Forward"])
add_recipe("recipe_plane_crash", "Plane Crash", [("inv_whiskey", 1.0), ("inv_bourbon", 1.0), ("inv_cola", 2.0)], ice=True, method="built", glassware="Highball", garnish=["Lime"], tags=["Classic", "Highball", "Whiskey"])
inv("inv_bourbon", "Bourbon", "Spirit", True)

(OUTPUT_DIR / "INVENTORY.json").write_text(json.dumps({"schema_version": "1.0.0", "inventory": inventory}, indent=2) + "\n", encoding="utf-8")
(OUTPUT_DIR / "RECIPES.json").write_text(json.dumps({"schema_version": "1.0.0", "recipes": recipes}, indent=2) + "\n", encoding="utf-8")
(OUTPUT_DIR / "INSTRUCTION_SETS.json").write_text(json.dumps({"schema_version": "1.0.0", "instruction_sets": instruction_sets}, indent=2) + "\n", encoding="utf-8")

print(f"Wrote {len(inventory)} inventory, {len(recipes)} recipes, {len(instruction_sets)} instruction sets")